import { ThemeConfig } from '../types/theme';
import { hexToRgbString, generatePrimaryRamp, darkenColor } from './colorEngine';

export function generateHomeAssistantThemeYaml(theme: ThemeConfig, backgroundSource: 'cdn' | 'local' | 'embedded' = 'local'): string {
  const { name, palette, engine, background, dark, light } = theme;
  const accent = palette.accent || palette.primary;
  const ramp = generatePrimaryRamp(accent);

  let bgValue = 'none';
  if (background.type === 'image') {
    if (backgroundSource === 'local') {
      const fileName = background.imageFileName || `${theme.id}.webp`;
      bgValue = `url('/local/ultimate-theme/backgrounds/${theme.id}/${fileName}')`;
    } else if (backgroundSource === 'embedded' && background.imageUrl) {
      bgValue = `url('${background.imageUrl}')`;
    } else {
      bgValue = `url('https://cdn.jsdelivr.net/gh/HomeRiz/hats@main/www/ultimate-theme/backgrounds/${theme.id}/default.webp')`;
    }
  } else if (background.type === 'gradient' && background.gradientString) {
    bgValue = background.gradientString;
  } else if (background.type === 'solid' && background.solidColor) {
    bgValue = `linear-gradient(0deg, ${background.solidColor}, ${background.solidColor})`;
  }

  const headerTint = background.headerTintColor || (background.avgColor ? darkenColor(background.avgColor, 0.25) : darkenColor(accent, 0.65));

  const tokenBlock = `
  # RGB palette tokens for standard components
  --token-rgb-primary: ${hexToRgbString(palette.primary)}
  --token-rgb-black: 0, 0, 0
  --token-rgb-white: 255, 255, 255
  --token-rgb-purple: ${hexToRgbString(palette.purple)}
  --token-rgb-pink: ${hexToRgbString(palette.pink)}
  --token-rgb-red: ${hexToRgbString(palette.red)}
  --token-rgb-deep-purple: ${hexToRgbString(palette.purple)}
  --token-rgb-indigo: ${hexToRgbString(palette.indigo)}
  --token-rgb-blue: ${hexToRgbString(palette.blue)}
  --token-rgb-light-blue: ${hexToRgbString(palette.lightBlue)}
  --token-rgb-cyan: ${hexToRgbString(palette.cyan)}
  --token-rgb-teal: ${hexToRgbString(palette.teal)}
  --token-rgb-green: ${hexToRgbString(palette.green)}
  --token-rgb-light-green: ${hexToRgbString(palette.green)}
  --token-rgb-lime: ${hexToRgbString(palette.green)}
  --token-rgb-yellow: ${hexToRgbString(palette.yellow)}
  --token-rgb-amber: ${hexToRgbString(palette.yellow)}
  --token-rgb-orange: ${hexToRgbString(palette.orange)}
  --token-rgb-deep-orange: ${hexToRgbString(palette.orange)}
  --token-rgb-brown: ${hexToRgbString(palette.brown)}
  --token-rgb-grey: ${hexToRgbString(palette.grey)}
  --token-rgb-state-icon: 255, 255, 255
  --token-size-radius-card: var(--ha-card-border-radius)
`.trimEnd();

  const rampBlock = ramp.map(r => `  --ha-color-primary-${r.step}: "${r.hex}"`).join('\n');

  const sheenGrad = `linear-gradient(${engine.sheenAngle}deg, rgba(255,255,255,${engine.sheenOpacity.toFixed(2)}) 0%, rgba(255,255,255,${(engine.sheenOpacity * 0.28).toFixed(2)}) 22%, rgba(255,255,255,0) 45%)`;

  const yamlContent = `---
# Generated by HATS (Home Assistant Theme Store) - https://github.com/HomeRiz/hats
"${name}":
  # Required by card-mod: must match theme name exactly
  card-mod-theme: "${name}"

  # Core HA Theme variables
  primary-color: "${accent}"
  accent-color: "${accent}"
  primary-text-color: "rgba(255, 255, 255, 0.96)"
  secondary-text-color: "rgba(228, 228, 232, 0.78)"
  disabled-text-color: "rgba(208, 208, 208, 0.45)"
  divider-color: "rgba(152, 152, 157, 0.28)"

  # HA Color Primary Ladder
${rampBlock}

  # Mode Tokens
${tokenBlock}

  # Card Geometry & Glass Engine
  ha-card-border-radius: "${engine.cardRadius}px"
  ha-card-border-width: "${engine.borderWidth}px"
  ha-card-border-color: "${engine.borderColor}"
  ha-card-backdrop-filter: "blur(${engine.blurAmount}px) saturate(${engine.saturateAmount})"
  ha-card-box-shadow: "${engine.insetShadow}"
  ha-dialog-surface-backdrop-filter: "none"

  # Ultimate Theme System Variables
  ultimate-background: "${bgValue}"
  ultimate-glow-color: "${engine.glowColor}"
  ultimate-sheen: "${sheenGrad}"
  ultimate-header-tint: "${headerTint}"

  # Light & Dark Mode definitions
  modes:
    dark:
      primary-background-color: "${dark.primaryBackground}"
      secondary-background-color: "${dark.secondaryBackground}"
      ha-card-background: "${dark.cardBackground}"
      primary-text-color: "${dark.textPrimary}"
      secondary-text-color: "${dark.textSecondary}"
    light:
      primary-background-color: "${light.primaryBackground}"
      secondary-background-color: "${light.secondaryBackground}"
      ha-card-background: "${light.cardBackground}"
      primary-text-color: "${light.textPrimary}"
      secondary-text-color: "${light.textSecondary}"

  # --------------------------------------------------------------------------
  # card-mod Injections: Root, View, Card, Sidebar, Header
  # --------------------------------------------------------------------------
  card-mod-root: |
    app-header {
      background: var(--ultimate-header-tint) !important;
      backdrop-filter: blur(20px) saturate(1.4) !important;
      -webkit-backdrop-filter: blur(20px) saturate(1.4) !important;
      border-bottom: 1px solid rgba(255, 255, 255, 0.08) !important;
    }

  card-mod-view: |
    hui-view {
      background: none !important;
    }
    :host {
      --ultimate-effective-bg: var(--ultimate-view-background, var(--ultimate-background));
    }
    :host::before {
      content: "";
      position: fixed;
      inset: 0;
      z-index: -2;
      background-image: var(--ultimate-effective-bg);
      background-position: center;
      background-size: cover;
      background-repeat: no-repeat;
      pointer-events: none;
    }
    :host::after {
      content: "";
      position: fixed;
      inset: 0;
      z-index: -1;
      background: ${engine.backgroundScrim || 'linear-gradient(180deg, rgba(0,0,0,0.15) 0%, rgba(0,0,0,0.35) 100%)'};
      pointer-events: none;
    }

  card-mod-card: |
    ha-card {
      position: relative;
      background: ${engine.glassTint} !important;
      border-radius: var(--ha-card-border-radius, ${engine.cardRadius}px) !important;
      border: ${engine.borderWidth}px solid ${engine.borderColor} !important;
      box-shadow: ${engine.insetShadow} !important;
      overflow: hidden;
      transition: transform 220ms ease, box-shadow 220ms ease, border-color 220ms ease;
    }
    ha-card::before {
      content: "";
      position: absolute;
      inset: 0;
      z-index: -1;
      backdrop-filter: var(--ha-card-backdrop-filter);
      -webkit-backdrop-filter: var(--ha-card-backdrop-filter);
      border-radius: inherit;
      pointer-events: none;
    }
    ha-card::after {
      content: "";
      position: absolute;
      inset: 0;
      z-index: 0;
      background: var(--ultimate-sheen);
      border-radius: inherit;
      pointer-events: none;
    }
    ${engine.hoverGlow ? `ha-card:hover {
      box-shadow: 0 0 ${engine.hoverGlowIntensity}px -4px var(--ultimate-glow-color), ${engine.insetShadow} !important;
      transform: translateY(-2px);
    }` : ''}
${theme.customCss ? `\n    /* Custom User Injected CSS */\n    ${theme.customCss.split('\n').join('\n    ')}` : ''}
`;

  return yamlContent;
}

export function generatePerViewSnippet(theme: ThemeConfig, viewPath = 'home', viewTitle = 'Main'): string {
  const bgUrl = theme.background.imageUrl || `/local/ultimate-theme/backgrounds/${theme.id}/default.webp`;
  return `- title: "${viewTitle}"
  path: "${viewPath}"
  icon: "mdi:view-dashboard"
  card_mod:
    style: |
      :host {
        --ultimate-view-background: url('${bgUrl}');
      }
`;
}
