import { ThemeConfig } from '../types/theme';
import { hexToRgbString, generatePrimaryRamp, darkenColor } from './colorEngine';

function svgToBase64DataUri(svg: string): string {
  let cleaned = svg.replace(/\r?\n/g, ' ').replace(/\s+/g, ' ').trim();
  if (!cleaned.includes('xmlns=')) {
    cleaned = cleaned.replace('<svg', '<svg xmlns="http://www.w3.org/2000/svg"');
  }
  let b64: string;
  if (typeof window !== 'undefined' && typeof window.btoa === 'function') {
    b64 = window.btoa(unescape(encodeURIComponent(cleaned)));
  } else {
    b64 = Buffer.from(cleaned, 'utf-8').toString('base64');
  }
  return `url('data:image/svg+xml;base64,${b64}')`;
}

export function generateHomeAssistantThemeYaml(theme: ThemeConfig, backgroundSource: 'cdn' | 'local' | 'embedded' = 'local'): string {
  const { name, palette, engine, background, dark, light, customSvgOverlay } = theme;
  const accent = palette.accent || palette.primary;
  const ramp = generatePrimaryRamp(accent);

  let baseBg = 'none';
  if (background.type === 'image') {
    if (backgroundSource === 'local') {
      const fileName = background.imageFileName || `${theme.id}.webp`;
      baseBg = `url('/local/ultimate-theme/backgrounds/${theme.id}/${fileName}')`;
    } else if (backgroundSource === 'embedded' && background.imageUrl) {
      baseBg = `url('${background.imageUrl}')`;
    } else {
      baseBg = `url('https://cdn.jsdelivr.net/gh/HomeRiz/hats@main/www/ultimate-theme/backgrounds/${theme.id}/default.webp')`;
    }
  } else if (background.type === 'gradient' && background.gradientString) {
    baseBg = background.gradientString;
  } else if (background.type === 'solid' && background.solidColor) {
    baseBg = `linear-gradient(0deg, ${background.solidColor}, ${background.solidColor})`;
  }

  let bgValue = baseBg;
  if (customSvgOverlay && customSvgOverlay.trim().startsWith('<svg')) {
    const svgDataUrl = svgToBase64DataUri(customSvgOverlay);
    bgValue = baseBg !== 'none' ? `${svgDataUrl}, ${baseBg}` : svgDataUrl;
  }

  const headerTint = background.headerTintColor || (background.avgColor ? darkenColor(background.avgColor, 0.25) : darkenColor(accent, 0.65));

  const tokenBlock = `
  # RGB palette tokens for standard components
  --token-rgb-primary: ${hexToRgbString(palette.primary)}
  --token-rgb-black: 0, 0, 0
  --token-rgb-white: 255, 255, 255
  --token-rgb-purple: ${hexToRgbString(palette.purple)}
  --token-rgb-pink: ${hexToRgbString(palette.pink)}
  --token-rgb-red: ${hexToRgbString(palette.red)}
  --token-rgb-deep-purple: ${hexToRgbString(palette.purple)}
  --token-rgb-indigo: ${hexToRgbString(palette.indigo)}
  --token-rgb-blue: ${hexToRgbString(palette.blue)}
  --token-rgb-light-blue: ${hexToRgbString(palette.lightBlue)}
  --token-rgb-cyan: ${hexToRgbString(palette.cyan)}
  --token-rgb-teal: ${hexToRgbString(palette.teal)}
  --token-rgb-green: ${hexToRgbString(palette.green)}
  --token-rgb-light-green: ${hexToRgbString(palette.green)}
  --token-rgb-lime: ${hexToRgbString(palette.green)}
  --token-rgb-yellow: ${hexToRgbString(palette.yellow)}
  --token-rgb-amber: ${hexToRgbString(palette.yellow)}
  --token-rgb-orange: ${hexToRgbString(palette.orange)}
  --token-rgb-deep-orange: ${hexToRgbString(palette.orange)}
  --token-rgb-brown: ${hexToRgbString(palette.brown)}
  --token-rgb-grey: ${hexToRgbString(palette.grey)}
  --token-rgb-state-icon: 255, 255, 255
  --token-size-radius-card: var(--ha-card-border-radius)
`.trimEnd();

  const rampBlock = ramp.map(r => `  --ha-color-primary-${r.step}: "${r.hex}"`).join('\n');

  const sheenGrad = `linear-gradient(${engine.sheenAngle}deg, rgba(255,255,255,${engine.sheenOpacity.toFixed(2)}) 0%, rgba(255,255,255,${(engine.sheenOpacity * 0.28).toFixed(2)}) 22%, rgba(255,255,255,0) 45%)`;

  const yamlContent = `---
# Generated by HATS (Home Assistant Theme Store) - https://github.com/HomeRiz/hats
"${name}":
  # Required by card-mod: must match theme name exactly
  card-mod-theme: "${name}"

  # Core HA Theme variables
  primary-color: "${accent}"
  accent-color: "${accent}"
  primary-text-color: "rgba(255, 255, 255, 0.96)"
  secondary-text-color: "rgba(228, 228, 232, 0.78)"
  disabled-text-color: "rgba(208, 208, 208, 0.45)"
  divider-color: "rgba(152, 152, 157, 0.28)"

  # Native Home Assistant Lovelace Background
  ultimate-background: "${bgValue}"
  background-image: "center / cover repeat fixed ${bgValue}"
  lovelace-background: var(--background-image)

  # Top App Header
  app-header-background-color: "${headerTint}"
  app-header-text-color: "#FFFFFF"
  app-header-selection-bar-color: "${accent}"

  # Sidebar (Left Menu Navigation) - Frosted glass container with high contrast
  sidebar-background-color: "rgba(18, 20, 32, 0.88)"
  sidebar-text-color: "rgba(255, 255, 255, 0.94)"
  sidebar-icon-color: "rgba(228, 228, 235, 0.82)"
  sidebar-selected-background-color: "rgba(${hexToRgbString(accent)}, 0.22)"
  sidebar-selected-text-color: "#FFFFFF"
  sidebar-selected-icon-color: "${accent}"
  sidebar-border-color: "rgba(255, 255, 255, 0.08)"

  # HA Color Primary Ladder
${rampBlock}

  # Mode Tokens
${tokenBlock}

  # Dropdowns & Web-Awesome UI Tokens (HA 2024.x - 2026.x)
  wa-shadow-m: var(--ha-card-box-shadow)
  wa-border-radius-s: var(--ha-card-border-radius)
  wa-border-radius-m: "${engine.cardRadius}px"
  wa-border-width-s: 0px
  wa-color-neutral-fill-normal: "rgba(255, 255, 255, 0.12)"
  ha-color-on-neutral-normal: var(--primary-text-color)
  ha-color-fill-primary-quiet-resting: "rgba(255, 255, 255, 0.12)"
  ha-color-fill-primary-quiet-hover: "rgba(255, 255, 255, 0.20)"

  # Card Geometry & Glass Engine
  ha-card-border-radius: "${engine.cardRadius}px"
  ha-card-border-width: "${engine.borderWidth}px"
  ha-card-border-color: "${engine.borderColor}"
  ha-card-glass-tint: "${engine.glassTint}"
  ha-card-glass-sheen: "${sheenGrad}"
  ha-card-backdrop-filter: "blur(${engine.blurAmount}px) saturate(${engine.saturateAmount})"
  ha-card-glass-inset-shadow: "${engine.insetShadow}"
  ha-card-box-shadow: "${engine.insetShadow}"
  ha-dialog-surface-backdrop-filter: "none"
  ultimate-transition: "box-shadow 220ms ease, transform 220ms ease"

  # Ultimate Theme System Variables
  ultimate-glow-color: "${engine.glowColor}"
  ultimate-sheen: "${sheenGrad}"
  ultimate-header-tint: "${headerTint}"

  # Light & Dark Mode definitions
  modes:
    dark:
      primary-background-color: "${dark.primaryBackground}"
      secondary-background-color: "${dark.secondaryBackground}"
      ha-card-background: "${dark.cardBackground}"
      primary-text-color: "${dark.textPrimary}"
      secondary-text-color: "${dark.textSecondary}"
      sidebar-background-color: "rgba(18, 20, 32, 0.88)"
      sidebar-text-color: "rgba(255, 255, 255, 0.94)"
      sidebar-icon-color: "rgba(228, 228, 235, 0.82)"
      sidebar-selected-background-color: "rgba(${hexToRgbString(accent)}, 0.22)"
      sidebar-selected-text-color: "#FFFFFF"
      sidebar-selected-icon-color: "${accent}"
      sidebar-border-color: "rgba(255, 255, 255, 0.08)"
    light:
      primary-background-color: "${light.primaryBackground}"
      secondary-background-color: "${light.secondaryBackground}"
      ha-card-background: "${light.cardBackground}"
      primary-text-color: "${light.textPrimary}"
      secondary-text-color: "${light.textSecondary}"
      sidebar-background-color: "rgba(255, 255, 255, 0.92)"
      sidebar-text-color: "#1E293B"
      sidebar-icon-color: "#475569"
      sidebar-selected-background-color: "rgba(${hexToRgbString(accent)}, 0.16)"
      sidebar-selected-text-color: "${accent}"
      sidebar-selected-icon-color: "${accent}"
      sidebar-border-color: "rgba(0, 0, 0, 0.08)"

  # --------------------------------------------------------------------------
  # card-mod Injections: Root, View, Card, Sidebar, Header, Config, Dialog, Profile
  # --------------------------------------------------------------------------
  card-mod-root: |
    /* Fixed viewport backdrop for iOS, Android & Desktop */
    :host::before {
      content: '';
      position: fixed;
      inset: 0;
      background-image: var(--ultimate-background);
      background-size: cover;
      background-position: center;
      background-repeat: repeat;
      z-index: -2;
      pointer-events: none;
    }
    :host::after {
      content: '';
      position: fixed;
      inset: 0;
      background: ${engine.backgroundScrim || 'linear-gradient(180deg, rgba(0,0,0,0.12) 0%, rgba(0,0,0,0.30) 100%)'};
      z-index: -1;
      pointer-events: none;
    }
    app-header {
      background: var(--ultimate-header-tint, ${headerTint}) !important;
      backdrop-filter: blur(20px) saturate(1.4) !important;
      -webkit-backdrop-filter: blur(20px) saturate(1.4) !important;
      border-bottom: 1px solid rgba(255, 255, 255, 0.08) !important;
    }
    ::-webkit-scrollbar { width: 8px; height: 8px; }
    ::-webkit-scrollbar-track { background: transparent; }
    ::-webkit-scrollbar-thumb {
      background: rgba(255, 255, 255, 0.22);
      border-radius: 8px;
    }
    ::-webkit-scrollbar-thumb:hover { background: var(--primary-color); }

  card-mod-sidebar: |
    :host {
      background-color: var(--sidebar-background-color, rgba(18, 20, 32, 0.88)) !important;
      backdrop-filter: var(--ha-card-backdrop-filter, blur(20px) saturate(1.4)) !important;
      -webkit-backdrop-filter: var(--ha-card-backdrop-filter, blur(20px) saturate(1.4)) !important;
      border-right: 1px solid var(--sidebar-border-color, rgba(255, 255, 255, 0.08)) !important;
      box-shadow: 4px 0 24px -8px rgba(0, 0, 0, 0.35) !important;
    }
    .menu,
    .panels-list,
    paper-listbox,
    ha-md-list {
      background: transparent !important;
    }
    .menu-text,
    .panel-title,
    .title,
    .name,
    .user-title,
    ha-md-list-item,
    ha-list-item-button,
    paper-icon-item {
      color: var(--sidebar-text-color, var(--primary-text-color)) !important;
      --md-list-item-label-text-color: var(--sidebar-text-color, var(--primary-text-color)) !important;
      --md-list-item-leading-icon-color: var(--sidebar-icon-color, var(--sidebar-text-color)) !important;
      --md-list-item-trailing-icon-color: var(--sidebar-icon-color, var(--sidebar-text-color)) !important;
      transition: background-color 150ms ease, color 150ms ease !important;
    }
    ha-md-list-item:hover,
    paper-icon-item:hover,
    ha-list-item-button:hover {
      background: var(--ha-color-fill-primary-quiet-hover, rgba(255, 255, 255, 0.08)) !important;
    }
    ha-md-list-item.selected,
    paper-icon-item.iron-selected,
    paper-icon-item[selected],
    ha-list-item-button.selected {
      background: var(--sidebar-selected-background-color, rgba(${hexToRgbString(accent)}, 0.22)) !important;
      color: var(--sidebar-selected-text-color, #FFFFFF) !important;
      --md-list-item-label-text-color: var(--sidebar-selected-text-color, #FFFFFF) !important;
      --md-list-item-leading-icon-color: var(--sidebar-selected-icon-color, var(--primary-color)) !important;
    }
    .profile {
      border-top: 1px solid var(--sidebar-border-color, rgba(255, 255, 255, 0.08)) !important;
    }

  card-mod-top-app-bar-fixed: |
    :host {
      backdrop-filter: var(--ha-card-backdrop-filter);
      -webkit-backdrop-filter: var(--ha-card-backdrop-filter);
    }

  card-mod-dialog: |
    :host {
      --dialog-backdrop-filter: none;
    }

  card-mod-view: |
    hui-view {
      background: none !important;
    }
    hui-view::before {
      content: '';
      position: fixed;
      inset: 0;
      background-image: var(--ultimate-view-background, var(--ultimate-background));
      background-size: cover;
      background-position: center;
      background-repeat: repeat;
      z-index: -2;
      pointer-events: none;
      opacity: var(--ultimate-view-background-opacity, 1);
    }

  card-mod-config: |
    ha-drawer {
      background-image: linear-gradient(180deg, rgba(0,0,0,0.12) 0%, rgba(0,0,0,0.30) 100%), var(--ultimate-background);
      background-size: cover;
      background-position: center;
      background-repeat: repeat;
      background-attachment: fixed;
    }
    ha-panel-config,
    partial-panel-resolver {
      background: transparent !important;
    }
    ha-card {
      background: var(--ha-card-glass-tint, ${engine.glassTint}) !important;
      backdrop-filter: var(--ha-card-backdrop-filter);
      -webkit-backdrop-filter: var(--ha-card-backdrop-filter);
      border-radius: var(--ha-card-border-radius, ${engine.cardRadius}px) !important;
      box-shadow: var(--ha-card-glass-inset-shadow, ${engine.insetShadow}) !important;
    }

  card-mod-profile: |
    ha-drawer {
      background-image: linear-gradient(180deg, rgba(0,0,0,0.12) 0%, rgba(0,0,0,0.30) 100%), var(--ultimate-background);
      background-size: cover;
      background-position: center;
      background-repeat: repeat;
      background-attachment: fixed;
    }
    ha-panel-profile,
    partial-panel-resolver {
      background: transparent !important;
    }
    ha-card {
      background: var(--ha-card-glass-tint, ${engine.glassTint}) !important;
      backdrop-filter: var(--ha-card-backdrop-filter);
      -webkit-backdrop-filter: var(--ha-card-backdrop-filter);
      border-radius: var(--ha-card-border-radius, ${engine.cardRadius}px) !important;
      box-shadow: var(--ha-card-glass-inset-shadow, ${engine.insetShadow}) !important;
    }

  card-mod-panel-custom: |
    ha-drawer {
      background-image: linear-gradient(180deg, rgba(0,0,0,0.12) 0%, rgba(0,0,0,0.30) 100%), var(--ultimate-background);
      background-size: cover;
      background-position: center;
      background-repeat: repeat;
      background-attachment: fixed;
    }
    ha-panel-custom,
    partial-panel-resolver {
      background: transparent !important;
    }

  card-mod-panel-iframe: |
    ha-drawer {
      background-image: linear-gradient(180deg, rgba(0,0,0,0.12) 0%, rgba(0,0,0,0.30) 100%), var(--ultimate-background);
      background-size: cover;
      background-position: center;
      background-repeat: repeat;
      background-attachment: fixed;
    }

  card-mod-panel-developer-tools: |
    ha-drawer {
      background-image: linear-gradient(180deg, rgba(0,0,0,0.12) 0%, rgba(0,0,0,0.30) 100%), var(--ultimate-background);
      background-size: cover;
      background-position: center;
      background-repeat: repeat;
      background-attachment: fixed;
    }
    ha-panel-developer-tools,
    partial-panel-resolver {
      background: transparent !important;
    }

  card-mod-card: |
    ha-card {
      position: relative;
      background: ${engine.glassTint} !important;
      border-radius: var(--ha-card-border-radius, ${engine.cardRadius}px) !important;
      border: ${engine.borderWidth}px solid ${engine.borderColor} !important;
      box-shadow: ${engine.insetShadow} !important;
      overflow: hidden;
      transition: transform 220ms ease, box-shadow 220ms ease, border-color 220ms ease;
    }
    ha-card::before {
      content: "";
      position: absolute;
      inset: 0;
      z-index: -1;
      backdrop-filter: var(--ha-card-backdrop-filter);
      -webkit-backdrop-filter: var(--ha-card-backdrop-filter);
      border-radius: inherit;
      pointer-events: none;
    }
    ha-card::after {
      content: "";
      position: absolute;
      inset: 0;
      z-index: 0;
      background: var(--ultimate-sheen);
      border-radius: inherit;
      pointer-events: none;
    }
    ${engine.hoverGlow ? `ha-card:hover {
      box-shadow: 0 0 ${engine.hoverGlowIntensity}px -4px var(--ultimate-glow-color), ${engine.insetShadow} !important;
      transform: translateY(-2px);
    }` : ''}
    :host(hui-heading-card) ha-card,
    :host(hui-glance-card) ha-card,
    :host(mushroom-title-card) ha-card,
    :host(mushroom-chips-card) ha-card,
    :host(.type-custom-bubble-card) ha-card,
    ha-card.text-only {
      background: none !important;
      backdrop-filter: none !important;
      -webkit-backdrop-filter: none !important;
      box-shadow: none !important;
      border: none !important;
    }
    :host(hui-heading-card) ha-card::before,
    :host(hui-heading-card) ha-card::after,
    :host(hui-glance-card) ha-card::before,
    :host(hui-glance-card) ha-card::after,
    :host(mushroom-title-card) ha-card::before,
    :host(mushroom-title-card) ha-card::after,
    :host(mushroom-chips-card) ha-card::before,
    :host(mushroom-chips-card) ha-card::after,
    :host(.type-custom-bubble-card) ha-card::before,
    :host(.type-custom-bubble-card) ha-card::after,
    ha-card.text-only::before,
    ha-card.text-only::after {
      content: none !important;
      background: none !important;
      backdrop-filter: none !important;
      -webkit-backdrop-filter: none !important;
    }
    :host(.type-custom-bubble-card) ha-card {
      border-radius: 0px !important;
    }
${theme.customCss ? `\n    /* Custom User Injected CSS */\n    ${theme.customCss.split('\n').join('\n    ')}` : ''}
`;

  return yamlContent;
}

export function generatePerViewSnippet(theme: ThemeConfig, viewPath = 'home', viewTitle = 'Main'): string {
  const bgUrl = theme.background.imageUrl || `/local/ultimate-theme/backgrounds/${theme.id}/default.webp`;
  return `- title: "${viewTitle}"
  path: "${viewPath}"
  icon: "mdi:view-dashboard"
  card_mod:
    style: |
      :host {
        --ultimate-view-background: url('${bgUrl}');
      }
`;
}
